/**
 * The body of the technical report, version 2. Every measured number is read from
 * research/data.json; the helpers are passed in from build.ts.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
export function body(h: {
  d: any;
  pct: (x: number, digits?: number) => string;
  ci: (c: [number, number]) => string;
  usd: (x: number, digits?: number) => string;
  n: (x: number) => string;
  cite: (...keys: string[]) => string;
  figure: (svg: string, caption: string, wide?: boolean) => string;
  table: (caption: string, head: string[], rows: (string | number)[][], note?: string) => string;
  fig: (name: string) => string;
  architecture: string;
  ed: (e: number, reader?: string) => any;
  field: (k: string, which: 'code' | 'withEngine') => any;
  fieldNames: Record<string, string>;
}): string {
  const { d, pct, ci, usd, n, cite, figure, table, fig, architecture, ed, field, fieldNames } = h;
  const J = d.endToEnd.jevCompared;
  const B = d.endToEnd.sonnet;
  const S = d.endToEnd.single.run;
  const F = d.endToEnd.jevFinal;
  const P = d.endToEnd.paired;
  const PU = d.endToEnd.pairedUnderspecified;
  const PS = d.endToEnd.single.paired;
  const PSU = d.endToEnd.single.pairedUnderspecified;
  const R = d.endToEnd.ratios;
  const RS = d.endToEnd.single.ratios;
  const BC = d.endToEnd.baselineConfidence;
  const floors = d.development.floors;
  const liheap = (run: any) => run.errors.filter((e: any) => e.program === 'liheap').length;
  const early = [1, 2, 3, 4, 5].map((e) => ed(e).rate);

  return `
<h1>Screening Households for U.S. Benefit Programs from a Short Description:<br>A Typed&#8209;Readout Decision Model Compared with Generative Baselines</h1>
<div class="authors">Jobin Ayathil</div>
<div class="meta">Independent &middot; jobinb6444@gmail.com &middot; Technical report, version 2, revised 22 September 2026 &middot; Code and data: github.com/0xjba/BennyFit</div>

<div class="abstract"><h2>Abstract</h2><p>
We describe BennyFit, a system that screens a household for ${d.setup.programs} U.S. federal and state benefit programs from a short plain-language description, asking a follow-up question only where an answer is expected to change the result. Numeric rules are implemented in code and checked against ${d.setup.conformance.total} hand-computed cases from primary sources (all agree). Judgements that depend on the description are posed as closed questions to a typed-readout model, TypeSafe's Jev (<code>${d.setup.jevModel}</code>), which returns a probability distribution over each question's options. We compare it with Claude Sonnet 5 answering the same questions in the same pipeline, in two configurations: under a JSON schema in batches, and in a single request without a schema. On ${J.specifiedHouseholds} synthetic held-out households that state every fact (${n(J.specified.total)} program verdicts), Jev made ${J.specified.wrong} errors, against ${B.specified.wrong} and ${S.specified.wrong} for the two baselines; the first difference is not significant and the second comes from a single repeated misreading. Jev returned a full result in a median ${J.medianSeconds.toFixed(1)} s against ${S.medianSeconds.toFixed(1)} to ${B.medianSeconds.toFixed(1)} s, at ${usd(J.costPerHouseholdUSD, 5)} per household at list price against ${usd(S.costPerHouseholdUSD, 3)} to ${usd(B.costPerHouseholdUSD, 3)} billed. On ${J.underspecifiedHouseholds} households that withhold how income is earned, Jev reached a wrong verdict in ${J.underspecifiedHouseholdsWrong} households against ${B.underspecifiedHouseholdsWrong} and ${S.underspecifiedHouseholdsWrong}, because it answered the unstated fact confidently instead of asking. For reading descriptions, code proposing candidate values with the model choosing among them read ${pct(ed(6, 'code+jev').rate)} of hand-labelled facts in fresh text, against ${pct(ed(6).rate)} for pattern-matching code alone. All households are synthetic and the samples are small.
</p></div>

<h2>1&nbsp;&nbsp;Introduction</h2>
<p>Eligible households do not all receive the benefits they qualify for. USDA estimates that 88% of people eligible for the Supplemental Nutrition Assistance Program (SNAP) received it in fiscal year 2022 ${cite('usda-rtin')}; the IRS estimates that about four in five eligible workers claim the Earned Income Tax Credit (EITC) ${cite('irs-eitc')}, and the Tax Policy Center reports that almost 80% of eligible tax units claimed it in tax year 2016 ${cite('tpc-eitc')}. Field experiments attribute part of the gap to information and effort rather than ineligibility. In a randomized trial with about 30,000 older adults likely eligible for SNAP, 6% of the control group enrolled within nine months, against 11% of a group sent information and 18% of a group sent information together with application assistance ${cite('finkelstein')}. In an IRS field experiment, simpler notices and more salient benefit information increased EITC claiming, while efforts to reduce stigma did not ${cite('bhargava')}.</p>
<p>A screener that tells a household which programs it probably qualifies for addresses the information part of this gap. The task has four parts: reading facts out of a description; judging criteria that depend on it, such as whether income comes from work or from benefits; applying numeric rules that vary by program, year and state; and deciding which missing fact, if any, is worth asking about. Following the model developer's guidance ${cite('ts-jag', 'ts-extract')}, the system keeps the third entirely in code and gives the model only closed questions. That division is a design choice, not a contribution of this report. The contributions are:</p>
<ul>
<li>A rule for choosing follow-up questions by expected value of information, which weighs each possible answer by the model's probability or, for presumed facts, by a declared rate at which the presumption fails, and declines to ask below a fixed floor (Section 3.4).</li>
<li>An observation about closed questions: without an explicit &ldquo;not stated&rdquo; option, a typed readout answers unstated facts confidently and the question-selection rule never asks them (Sections 5.3 and 6).</li>
<li>An evaluation that measures rules, reading and end-to-end decisions separately, chooses its threshold on development data by a rule fixed in advance, and compares the typed readout with a generative model in two configurations on the same held-out households (Sections 4 and 5).</li>
</ul>

${figure(architecture, 'Architecture. Code finds candidate amounts and counts people; the criterion set is instantiated per household member; the typed readout answers every criterion and reading question in one request; the rules engine computes verdicts in integer cents; question selection either returns the verdicts or one question, whose answer is appended to the state for the next pass.')}

<h2>2&nbsp;&nbsp;Background</h2>
<h3>2.1&nbsp;&nbsp;Typed readout</h3>
<p>Jev is described by its developer as a &ldquo;System One&rdquo; model: it is sent a <i>state</i> (here, the household description) and a map of typed questions, and returns for each question either the probability that a yes/no statement is true (a <i>noul</i>) or a distribution over the options of a <i>choice</i> ${cite('ts-api')}. It does not generate text. All questions are evaluated against the same state in one request; <code>jev-1.13.0</code> has a 64k-token context and a list price of $0.042 per million input tokens, with output tokens not charged ${cite('ts-api')}.</p>
<h3>2.2&nbsp;&nbsp;Generation with structured output</h3>
<p>The common alternative is to ask a generative model to write its answers as JSON, often under a schema enforced by constrained decoding ${cite('anthropic-so')}. A schema can restrict each answer to that question's own options; it does not supply a distribution over them. A confidence obtained by asking the model to state one is itself generated text; such verbalized confidence has been found to be overconfident relative to accuracy ${cite('xiong')}, which says nothing about how it compares with a threshold chosen for a different model. Format restrictions can also reduce reasoning performance ${cite('tam')}. Calibration of model probabilities more generally is studied in ${cite('guo', 'kadavath')}.</p>
<h3>2.3&nbsp;&nbsp;Value of information</h3>
<p>Whether to ask a question is a decision about the value of the information it would yield: the expected improvement in outcome from learning the answer, weighed against the cost of asking ${cite('howard')}. Here the outcome is the set of program verdicts and their dollar values, and the cost of asking is a person's time.</p>

<h2>3&nbsp;&nbsp;System</h2>
<p>Figure 1 shows the components and the loop.</p>
<h3>3.1&nbsp;&nbsp;Rules</h3>
<p>The system covers ${d.setup.programs} programs: ${d.setup.programNames.join(', ')}. Every threshold is stored with the period it applies to and the source it was read from; the table in force on the screening date is selected, and where a new year's table has not been published the previous one is used with a visible notice. Money is held in integer cents and rounded where the regulation says to round ${cite('cfr273')}. State variation is applied for SNAP broad-based categorical eligibility, Medicaid expansion and state earned income credits across ${d.setup.jurisdictions} jurisdictions. Three tests that compare numbers are computed in code rather than read from the description: the dependent care credit's requirement of a child under 13 ${cite('irc')}, the Veterans Pension's requirement of age 65 or a disability ${cite('va')}, and Medicare enrolment, which a stated age under 65 without mention of a disability rules out ${cite('medicare')}.</p>
<h3>3.2&nbsp;&nbsp;Criteria</h3>
<p>Each program is a set of criteria, each a noul or a choice with instructions written to be read literally, instantiated once per relevant household member; a held-out household produced a median of ${J.medianCriteria}. Some criteria carry a <i>presumption</i>, an option that stands when the model is unsure (for example, that a claimant has a Social Security number valid for work), classed as routine or material and shown with the verdict as a stated condition. A choice may offer a <i>not stated</i> option; when the model selects it, that probability is removed, the rest is renormalised so the model's lean still decides the provisional verdict, and the answer's confidence is capped at the probability that the description did state it.</p>
<h3>3.3&nbsp;&nbsp;Confidence</h3>
<p>For an answer with distribution <i>p</i> over <i>K</i> options the system uses normalised entropy,</p>
<p class="eq">c(p) = 1 &minus; H(p) / ln K,&nbsp;&nbsp;&nbsp; H(p) = &minus;&Sigma;<sub>k</sub> p<sub>k</sub> ln p<sub>k</sub>,<span class="no">(1)</span></p>
<p>and treats an answer with <i>c</i> &lt; &tau; as unsettled. The developer's own statistic is (K&middot;max<sub>k</sub> p<sub>k</sub> &minus; 1)/(K &minus; 1) ${cite('ts-conf')}; the entropy form was kept so that nouls and choices share one definition. &tau; = ${d.setup.tauChosen} was chosen on the development households for Jev (Section 4.4). For a yes/no answer, <i>c</i> &ge; ${d.setup.tauChosen} requires the larger probability to be at least ${BC.statedNeededToClearTau.twoOptions.toFixed(2)}.</p>
<h3>3.4&nbsp;&nbsp;Question selection</h3>
<p>For each unsettled criterion <i>q</i> with options <i>o</i>, the rules engine is run with <i>q</i> pinned to each option, giving total annual dollar values <i>V</i>(<i>o</i>); <i>V</i><sub>0</sub> is the total under current answers. The expected change from learning <i>q</i> is</p>
<p class="eq">E[&Delta;<sub>q</sub>] = &Sigma;<sub>o</sub> b<sub>q</sub>(o) &middot; |V(o) &minus; V<sub>0</sub>|,<span class="no">(2)</span></p>
<p>where <i>b<sub>q</sub></i> is the belief over options. For criteria without a presumption <i>b<sub>q</sub></i> is the model's distribution. For presumed criteria it places 1 &minus; &epsilon; on the presumed option, with &epsilon; = 0.05 for routine and 0.20 for material presumptions: when a description is silent, the model's distribution measures whether the text says so, not how often the presumption is false in the population. The two values of &epsilon; are declared assumptions; they were not tuned, because presumptions are never false in the synthetic households and tuning would drive &epsilon; to zero. The criterion with the largest E[&Delta;] is asked if it exceeds $25 a year, a floor chosen on the development households (Section 5.4); at most three questions are asked. An earlier version ranked by the spread max<sub>o</sub> V(o) &minus; min<sub>o</sub> V(o), which ignores <i>b<sub>q</sub></i>. If the household size cannot be read it is asked first, and the number is taken from the reply in code.</p>
<h3>3.5&nbsp;&nbsp;Reading the description</h3>
<p>Following ${cite('ts-extract')}, code over-finds every span that could be an amount of money, excluding only ages, counts of people, years and single digits without a currency mark, and merges ranges such as &ldquo;$300&ndash;$400&rdquo; into one candidate at the midpoint. For each candidate the model answers two choices: its role (income, housing, care, utilities, medical, child support paid, savings, other) and its period (weekly, every two weeks, twice a month, monthly, yearly, once, not stated). Code copies the chosen span's value, converts it to a monthly figure and sums multiple incomes; the model never writes a number. Household size and the number of children are counted by code. The model's own counts fill a count that code could not read when its confidence is at least 0.6, and cause the household to be asked when the two disagree.</p>

<h2>4&nbsp;&nbsp;Evaluation design</h2>
<h3>4.1&nbsp;&nbsp;Three measurements</h3>
<p>Accuracy is reported as three separate measurements, because they fail in different ways: (i) whether the rules match their sources, (ii) whether facts are read correctly out of prose, and (iii) whether the whole system reaches the right verdict.</p>
<h3>4.2&nbsp;&nbsp;Rules conformance</h3>
<p>${d.setup.conformance.total} cases each state an input and an expected figure worked out by hand from a primary source: USDA's worked SNAP example, IRS revenue procedure tables, Medicare limits, VA pension rates and the statutory tests above. No expected figure is produced by the code under test.</p>
<h3>4.3&nbsp;&nbsp;Reading sets</h3>
<p>Reading is scored on short descriptions written in the forms people use (&ldquo;me + 2 kids&rdquo;, &ldquo;45k a year&rdquo;, &ldquo;paid $1,350 on the 1st and the 15th&rdquo;), each labelled by hand with up to seven fields. A held-out set of twenty is scored once; once any code is changed in response to it, it joins the development set and a new held-out set is written. Six editions were written this way; the development set now holds ${d.setup.readingDevCases} descriptions. All sets were written and labelled by the author, who also wrote both readers; the sixth set was written after the candidate reader existed, though before either reader was run on it. Income is also scored as a monthly figure, so that equivalent statements in different units are not counted as errors; this was decided before the sixth set was scored.</p>
<h3>4.4&nbsp;&nbsp;End-to-end households</h3>
${table('Validation households by slice and split. Every third household is held out.', ['Slice', 'Development', 'Held out'], Object.entries(d.setup.gold.slices).map(([k, v]) => [k.replace('_', ' '), (v as any).dev, (v as any).holdout]).concat([['Total', d.setup.gold.dev, d.setup.gold.holdout]]))}
<p>${d.setup.gold.total} synthetic households were generated from stored facts and rendered as prose, and the correct verdict for each program was computed from those facts by the rules layer. <i>Clear eligible</i> households qualify for several programs and <i>clear ineligible</i> ones for none; <i>mixed</i> ones qualify for some. <i>Underspecified</i> households omit one fact by construction; in every one it is the same fact, whether income comes from work or from benefits. <i>Adversarial</i> households contain one of two traps: a qualifying program or income source mentioned in passing rather than claimed, or income stated weekly or every two weeks, which is understated several times if read as monthly. Follow-up questions are answered by a simulated respondent that replies truthfully from the stored facts. &tau; was chosen on the development households by a rule fixed before the sweep: highest mean balanced accuracy, ties to fewer questions, then lower &tau;. The held-out households are scored once per system version.</p>
<h3>4.5&nbsp;&nbsp;Baselines</h3>
<p>Each baseline replaces only the source of criterion answers; the reader, rules, follow-up loop, respondent and answer key are unchanged. Claude Sonnet 5 (via OpenRouter) receives the same description and criteria and returns, for each criterion, one of its options and a stated confidence <i>s</i>, converted to a distribution with max(<i>s</i>, 1/K) on the chosen option and the remainder shared evenly. In the <i>batched schema</i> configuration its reply is constrained by a JSON schema whose every answer is an enumeration of that criterion's options; a schema covering a whole household exceeded the provider's limit on compiled grammar size, so criteria were sent in parallel batches of ${d.setup.baselineBatchSize}, each carrying the full description. In the <i>one request</i> configuration all criteria go in a single request without a schema, and answers are validated in code, so an answer outside a criterion's options would be counted as a fault; this is close to asking the model once for every fact and applying the rules in code. The model does not accept a temperature parameter. Both configurations use the typed readout's &tau;; how that threshold interacts with stated confidence is reported in Section 5.3.</p>
<h3>4.6&nbsp;&nbsp;Metrics</h3>
<p>The primary measure is the number of wrong program verdicts on fully specified households. Per program, balanced accuracy (the mean of true-positive and true-negative rates) ${cite('brodersen')} is reported where both rates are defined; a program with no eligible or no ineligible held-out household is reported as not estimable and left out of means. Overall per-verdict accuracy is given with 95% Wilson intervals ${cite('wilson')}, but most verdicts are easy negatives (a household with no children is correctly ineligible for Head Start), so it is dominated by them. Paired comparisons on identical verdicts use an exact McNemar test ${cite('mcnemar')}; verdicts within one household are not independent, so these tests overstate the effective sample size, and for the underspecified slice results are also given per household. Latency is the median wall-clock time to a full result including follow-ups. The typed readout's cost is its input tokens at list price; the baselines' is what OpenRouter billed.</p>

<h2>5&nbsp;&nbsp;Results</h2>
<h3>5.1&nbsp;&nbsp;Rules</h3>
<p>All ${d.setup.conformance.total} conformance cases agree with their sources. Four rule errors were found during the work and each is now pinned by a case: the EITC maximum at the plateau was computed as $8,230.50 against a published $8,231; the dependent care credit counted children aged 13 or over; the Veterans Pension omitted its age-or-disability requirement; and pay received twice a month was treated as monthly, halving income. The second was found because the first end-to-end run disagreed with the answer key on a household with children aged 14 and 15, and the key itself was wrong.</p>
<h3>5.2&nbsp;&nbsp;Reading</h3>
${figure(fig('fig2-reading-editions'), 'Share of hand-labelled facts read correctly on each held-out reading set, when first scored, with 95% Wilson intervals. Sets 1 to 5 were scored by the pattern-matching reader alone; set 6 by both readers once each.')}
<p>Across five editions the pattern-matching reader scored between ${pct(Math.min(...early))} and ${pct(Math.max(...early))} on unseen text while its development score rose above 99%: each fresh set exposed new phrasings. On the sixth set, code alone read ${ed(6).correct} of ${ed(6).total} facts (${pct(ed(6).rate)}, CI ${ci(ed(6).ci)}) and code with the model choosing among candidates read ${ed(6, 'code+jev').correct} of ${ed(6, 'code+jev').total} (${pct(ed(6, 'code+jev').rate)}, CI ${ci(ed(6, 'code+jev').ci)}). Monthly income was right in ${field('incomeMonthly', 'withEngine').correct} of ${field('incomeMonthly', 'withEngine').total} descriptions against ${field('incomeMonthly', 'code').correct} of ${field('incomeMonthly', 'code').total}. The largest gains were descriptions with two incomes (base pay and tips; SSI and occasional babysitting), which code resolved to the first amount, and one in which code read a $140 electricity bill as the household's income. With twenty descriptions the intervals are wide, and the set was written by the reader's author (Section 4.3).</p>
${figure(fig('fig3-reading-by-field'), 'Held-out reading set 6 by field, for code alone and for code with the model choosing among candidates.')}
${table('Facts the candidate reader got wrong or left open on held-out set 6.', ['Case', 'Field', 'Expected', 'Read'], d.reading.sixMisses.map((m: any) => [m.id, fieldNames[m.field] ?? m.field, String(m.expected), m.got === null ? 'asked' : String(m.got).startsWith('not logged') ? 'wrong (value not logged)' : String(m.got)]), 'The scoring run logged the value only where the two readers disagreed; where both were wrong, only the fact of the error was recorded.')}

<h3>5.3&nbsp;&nbsp;End to end, against the baselines</h3>
${table('Held-out households, same pipeline, three sources of criterion answers.', ['', 'Jev', 'Sonnet 5, batched schema', 'Sonnet 5, one request'], [
  ['Wrong verdicts, fully specified (of ' + n(J.specified.total) + ')', J.specified.wrong, B.specified.wrong, S.specified.wrong],
  ['&nbsp;&nbsp;false positive / false negative', `${J.specified.falsePositive} / ${J.specified.falseNegative}`, `${B.specified.falsePositive} / ${B.specified.falseNegative}`, `${S.specified.falsePositive} / ${S.specified.falseNegative}`],
  ['&nbsp;&nbsp;per-verdict accuracy, 95% Wilson interval', ci(J.specified.ci), ci(B.specified.ci), ci(S.specified.ci)],
  [`Mean balanced accuracy, ${J.estimablePrograms} estimable programs`, pct(J.meanBalancedAccuracy, 2), pct(B.meanBalancedAccuracy, 2), pct(S.meanBalancedAccuracy, 2)],
  ['Underspecified households with a wrong verdict (of ' + J.underspecifiedHouseholds + ')', J.underspecifiedHouseholdsWrong, B.underspecifiedHouseholdsWrong, S.underspecifiedHouseholdsWrong],
  ['&nbsp;&nbsp;wrong verdicts (of ' + J.underspecified.total + ')', J.underspecified.wrong, B.underspecified.wrong, S.underspecified.wrong],
  ['Follow-up questions, total (median)', `${J.questionsTotal} (${J.questionsMedian})`, `${B.questionsTotal} (${B.questionsMedian})`, `${S.questionsTotal} (${S.questionsMedian})`],
  ['Median seconds to a full result', J.medianSeconds.toFixed(1), B.medianSeconds.toFixed(1), S.medianSeconds.toFixed(1)],
  ['Input / output tokens', `${n(J.usage.inputTokens)} / ${n(J.usage.outputTokens)}`, `${n(B.usage.inputTokens)} / ${n(B.usage.outputTokens)}`, `${n(S.usage.inputTokens)} / ${n(S.usage.outputTokens)}`],
  ['Cost per household (USD)', `${usd(J.costPerHouseholdUSD, 5)} at list price`, `${usd(B.costPerHouseholdUSD, 3)} billed`, `${usd(S.costPerHouseholdUSD, 3)} billed`],
  ['Answers outside a criterion&rsquo;s options, or missing', 'not possible', String(Object.values(d.endToEnd.generationFaults).reduce((a: number, b: any) => a + b, 0)), String(Object.values(d.endToEnd.single.generationFaults).reduce((a: number, b: any) => a + b, 0))],
], `${J.households} held-out households: ${J.specifiedHouseholds} fully specified, ${J.underspecifiedHouseholds} underspecified; ${J.programs} programs each; &tau; = ${J.tau} throughout. FDPIR has no eligible held-out household and is not estimable. The typed readout's column is the run made on the same version of the system as the baselines.`)}
<p><b>Fully specified households.</b> Against the batched schema baseline, the two sources of answers agreed on ${P.bothRight} of ${n(J.specified.total)} verdicts; Jev alone was right on ${P.onlyJev} and the baseline alone on ${P.onlySonnet} (exact McNemar <i>p</i> = ${P.mcnemarP.toFixed(2)}). With ten discordant verdicts the test has little power: no difference was detected, which is not evidence that there is none. Against the one-request baseline, Jev alone was right on ${PS.onlyJev} and the baseline alone on ${PS.onlySonnet} (<i>p</i> = ${PS.mcnemarP.toFixed(3)}), but all ${S.specified.wrong} of that baseline's errors, and ${liheap(B)} of the batched baseline's ${B.specified.wrong}, are the same misreading: households whose rent included utilities were judged not to pay for heating, where the criterion states that energy paid through the rent counts. The difference therefore reflects one criterion's wording meeting one model, not a general gap. Jev's ${J.specified.wrong} errors were two Child Tax Credit false negatives and one Extra Help false positive for a 62-year-old, the case that motivated the Medicare check in Section 3.1.</p>
<p><b>Underspecified households.</b> All ${J.underspecifiedHouseholds} withhold the same fact, so this slice tests one question. Jev reached a wrong verdict in ${J.underspecifiedHouseholdsWrong} households, the batched baseline in ${B.underspecifiedHouseholdsWrong} and the one-request baseline in ${S.underspecifiedHouseholdsWrong} (paired over verdicts, <i>p</i> = ${PU.mcnemarP.toFixed(3)} and ${PSU.mcnemarP.toFixed(2)}; the first figure counts correlated verdicts as independent and should not be read as significance). Jev answered where income came from with high confidence in households that did not say, so the question was not asked. The batched baseline's advantage comes largely from the threshold: its stated confidences had a median of ${BC.batchedSchema.statedMedian.toFixed(2)}, and ${pct(BC.batchedSchema.belowTauShare, 0)} of its answers fell below &tau; once converted, so it asked the maximum three questions in ${B.questionsHistogram[3]} of ${B.households} households and reached the withheld fact more often, at the cost of more questions for every household. In one request its stated confidences were higher (median ${BC.singleRequest.statedMedian.toFixed(2)}; ${pct(BC.singleRequest.belowTauShare, 0)} below &tau;), it asked ${S.questionsTotal} questions, and its underspecified result was close to Jev's. &tau; was not re-tuned for the baselines: doing so properly on the development households was outside the budget of this study.</p>
${figure(fig('fig4-per-program'), 'Balanced accuracy per program on fully specified held-out households, with the number of eligible households in brackets. Rates resting on one or two eligible households are fragile.')}
${figure(fig('fig5-time-cost'), `Median time to a full result and cost per household. Against the one-request baseline, the typed readout was ${RS.speed.toFixed(1)} times faster and ${Math.round(RS.cost)} times cheaper; against the batched baseline, ${R.speed.toFixed(1)} and ${Math.round(R.cost)} times. These ratios depend on the pipeline design (how many questions per request, how many passes) and on each provider's pricing, not only on the models.`)}

<h3>5.4&nbsp;&nbsp;Question selection</h3>
<p>Figure 6 shows the &tau; sweep on development households: accuracy was flat from 0.3 to 0.7 and lower at 0.2, and the rule selected 0.3. Figure 7 shows the expected-value floor on development households, after the Veterans Pension correction: any floor from $25 to $250 reduced questions from ${floors[0].questions} to between ${Math.min(...floors.slice(1).map((f: any) => f.questions))} and ${Math.max(...floors.slice(1).map((f: any) => f.questions))}, with fully specified errors between ${Math.min(...floors.map((f: any) => f.specifiedWrong))} and ${Math.max(...floors.map((f: any) => f.specifiedWrong))} of ${n(81 * 21)} verdicts, a range consistent with run-to-run variation. $25 was chosen as the lowest floor giving the reduction.</p>
<div class="pair">${figure(fig('fig6-tau-sweep'), 'Confidence threshold on development households: mean balanced accuracy and median questions.', false)}${figure(fig('fig7-floor-sweep'), 'Expected-value floor on development households: questions asked and the share whose answer changed the result.', false)}</div>
${table('Development households, successive changes. Each row includes the changes above it.', ['Change', 'Questions', 'Moved the result', 'Deciding fact first', 'Specified errors'], d.development.stages.map((s: any) => [s.stage, s.questions, pct(s.useful.rate), pct(s.questionRelevance, 0), s.specifiedWrong]), `101 development households, 20 underspecified; specified errors are out of ${n(81 * 21)} verdicts. The first row already uses expected-value ranking. Differences of a few errors, and of one or two in twenty for &ldquo;deciding fact first&rdquo;, are within run-to-run variation; only the change in questions asked is clearly larger than it.`)}
<p>On the held-out households the version with expected-value ranking and the candidate reader asked ${F.questionsTotal} questions against ${J.questionsTotal} for the version compared with the baselines, with a median of ${F.questionsMedian} per household, ${F.usefulQuestions.moved} of the ${F.usefulQuestions.answered} (${pct(F.usefulQuestions.rate)}) changing the result. It made ${F.specified.wrong} errors on fully specified households and a wrong verdict in ${F.underspecifiedHouseholdsWrong} of ${F.underspecifiedHouseholds} underspecified ones, both in line with before. Its median time rose to ${F.medianSeconds.toFixed(1)} s because reading adds a request. The last row of Table 4 was prompted by held-out errors and has not been scored on held-out households.</p>
${figure(fig('fig8-questions-histogram'), 'Follow-up questions per held-out household: the version compared with the baselines (spread ranking) and the version with expected-value ranking and the candidate reader.', false)}

<h2>6&nbsp;&nbsp;Discussion</h2>
<p>On these data, the typed readout's verdicts were at least as accurate as a general-purpose model's in the same pipeline, and it produced them an order of magnitude faster and two orders of magnitude cheaper. The cost and speed gap has two sources that this study cannot separate: the interface (one request for every question, input-only pricing, distributions returned directly) and the providers' prices. It is also sensitive to pipeline design, as the difference between the two baseline configurations shows.</p>
<p>The distribution is what the question selector consumes, and that is where the typed readout's main failure appeared. Weighting questions by the model's distribution cut the number asked by about a third, but a closed question with no way to say the description is silent forces a confident choice, and a confident answer is never asked about. The <i>not stated</i> option addresses this; on development households it raised how often the withheld fact was asked first, but it has not been measured on held-out data. For the generative baselines, stated confidence set against a threshold chosen for another model governed how many questions were asked, and so how the underspecified households came out; comparing question-asking behaviour across models needs a threshold set for each.</p>
<p>Every error found in the rules was an arithmetic or threshold error in code, found by comparison with a source. Every reading gain came from delegating &ldquo;what is this amount&rdquo; to the model while keeping the number itself in code.</p>

<h2>7&nbsp;&nbsp;Limitations</h2>
<ul>
<li><b>Synthetic households.</b> Households and their descriptions were generated from templates, and the answer key was computed by the same rules layer the system uses. The end-to-end figures measure reading, judgement and question selection against a known key, not agreement with eligibility decisions by agencies, and will overstate accuracy on real descriptions, which are less regular.</li>
<li><b>Sample size.</b> ${J.specifiedHouseholds} fully specified and ${J.underspecifiedHouseholds} underspecified held-out households; several programs have one or two eligible households, one has none, and the underspecified slice tests a single withheld fact. Paired tests treat correlated verdicts as independent.</li>
<li><b>Repeatability.</b> Both models returned slightly different answers across runs. Jev's held-out run was repeated after a correction to the rules and the answer key; two of its three errors recurred, and the third error of the first run was the answer key's. Each baseline configuration was run once, and the model does not accept a temperature setting.</li>
<li><b>Baselines.</b> One generative model, one prompt, and a threshold chosen for the typed readout rather than for it.</li>
<li><b>Simulated respondent.</b> Follow-up answers were always truthful and complete.</li>
<li><b>Held-out reuse.</b> Two changes (the Medicare check and the <i>not stated</i> option) were prompted by held-out errors; they are reported on development data only.</li>
<li><b>Authorship of test data.</b> The reading sets were written by the author of the readers.</li>
<li><b>Coverage.</b> English only; state-specific rules for three program families; screening estimates, not determinations.</li>
<li><b>Prices</b> are the typed readout's list price and the baselines' billed cost on 21 and 22 September 2026.</li>
</ul>

<h2>8&nbsp;&nbsp;Conclusion</h2>
<p>A screening system that keeps every numeric rule in code and asks a typed-readout model only closed questions made ${J.specified.wrong} errors in ${n(J.specified.total)} held-out verdicts, against ${B.specified.wrong} and ${S.specified.wrong} for a general-purpose model in two configurations of the same pipeline, while returning results ${RS.speed.toFixed(0)} to ${R.speed.toFixed(0)} times faster at a small fraction of the cost. The samples are small and synthetic, and no accuracy advantage over the stronger baseline configuration was detected. The model's probability outputs made it possible to select follow-up questions by expected value, and exposed a failure mode, confident answers about unstated facts, that an explicit <i>not stated</i> option is designed to address. The main open question is how these results hold on descriptions written by real applicants.</p>

<h2>Reproducibility</h2>
<p class="small">The code, rules, validation households, reading sets, run records and this report's data and figures are in the repository at commit ${d.commit}. <code>npx tsx eval/run.ts</code> scores the system; <code>--sweep-only</code> chooses &tau; on development households; <code>ENGINE=baseline</code> runs a generative baseline, and <code>OPENROUTER_STRUCTURED=0</code> selects the one-request configuration; <code>npx tsx eval/read-dev.ts</code> compares the readers; <code>research/baseline-confidence.ts</code> measures the baselines' stated confidences. <code>research/data.ts</code> computes every number in this report from the committed run files, and <code>research/charts.py</code> draws every figure from its output.</p>

<h2>Revision history</h2>
<p class="small"><b>Version 2, 22 September 2026.</b> Added a second baseline configuration (one request, no schema). Reported error counts as the primary measure; balanced accuracy is now reported as not estimable for programs with no eligible or no ineligible household and left out of means. Reported the underspecified slice per household and stated that it tests a single withheld fact. Measured how the threshold interacts with the baselines' stated confidence. Stated the typed readout's cost at list price. Corrected the description of repeated runs, defined the validation slices, disclosed the authorship of the reading sets, and reframed the contributions. <b>Version 1, 21 September 2026.</b> First release.</p>
`;
}
